### ISSUE TITLE
test app error.

### ISSUE THREAD

**Issue by meitiever** [zougloub/libseek#3]
./build/seek-test
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open device
Aborted (core dumped)

PS: Ubuntu 14.04.4
Device: seek thermal CompactXR(android edition)

Any idea how to fix this?
thanks

**Comment by bartashevich** [comment]
try with sudo, worked for me

**Comment by zougloub** [comment]
Hi guys, sorry for not getting back... USB devices on Linux are used as device files which have permissions that could be dependent on the distro. Additional udev rules can be created to set up a device for a specific group. On my machine, USB devices are accessible to users in the `usb` group, and adding oneself to it makes it work without using administrator privileges.  And there is a group `plugdev` that gets access to other devices. I am not sure how much of this is standard, I didn't take the time to look.

I lent my thermal cam to a friend, but if you can find the vendor ID / product ID of the seek camera(s) it would be possible to add an udev rule looking like:

`/etc/udev/rules.d/98-seek-thermal`:

```
ATTR{idVendor}=="TODO", ATTR{idProduct}=="TODO", GROUP="plugdev or seek", MODE="0660"
```

Regards,
