### ISSUE TITLE
no module found named cv2

### ISSUE THREAD

**Issue by mathurawasirishabh** [zougloub/libseek#5]
when i run following command it gives following errror:
pi@raspberrypi:~/libseek $ ./test-calib.py 
Traceback (most recent call last):
  File "./test-calib.py", line 6, in <module>
    import cv2
ImportError: No module named cv2

**Comment by billrock** [comment]
The required dependency OpenCV 2 is not installed.

**Comment by zougloub** [comment]
Thanks  @billrock. @mathurawasirishabh sorry, `cv2` is a very common Python library and I hadn't bothered to document it. But I guess googling `ImportError: No module named cv2` should have returned a lot of results :)
